name: test_expression
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  expressions:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "The job is running"
        if: ${{ github.event_name == 'push' || github.ref == 'refs/heads/main' }}
        #        if: ${{ !contains(github.event.head_commit.message, 'WIP') }}
