name: force failure/success
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check for deprecated functions
        run: |
          deprecated=true
          if [[ $deprecated ]]; then
            echo "::warning::Deprecated function found"
          fi
