name: first workflow
on:
  push:
     branches:
       - asd
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      - name: print first meesages
        run: echo "print first meesages"
      - name: List Sources
        run: ls -la

   
