on:
  workflow_dispatch:
    inputs:
      environment:
         description: "Please add the correct env name"
         required: true
         default: "staging"
         type: choice
         options: 
            - staging
            - production
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: run first job
        run: echo "Hello Manual ${{inputs.environment}}"
    
